### ISSUE TITLE
Django Q reschedule long tasks

### ISSUE THREAD

**Issue by gorkemyontem** [gorkemyontem/SWE-573-2020#26]
Django Q create a lot of same tasks
My settings: 

```
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 2,
    'timeout': 4800, 
    'retry': 120,
    'queue_limit': 500,
    'orm': 'default'
}
```

**Comment by gorkemyontem** [comment]
Might be related https://github.com/Koed00/django-q/issues/238

**Comment by gorkemyontem** [comment]
Related to this: https://github.com/Koed00/django-q/issues/183

**Comment by gorkemyontem** [comment]
Fixed by changing settings. 
```
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 2,
    'timeout': 4800, 
    'retry':  4801,
    'queue_limit': 500,
    'orm': 'default'
}
```
Official document: https://django-q.readthedocs.io/en/latest/configure.html#retry

**Comment by gorkemyontem** [comment]
@uskudarli This problem was actually very hard to find for me. 
The thing is, If the task takes longer than the retry time setting, djangoQ thinks that the task has failed. And retries it. If you have 60 seconds for retry option and if your scheduled task takes let's say 100 seconds, you will see 1 additional task scheduled. 
It explained very well here https://django-q.readthedocs.io/en/latest/configure.html#retry

**Comment by dnk8n** [comment]
What does one do if a task could take 1, 2, 3 who knows how many hours? The system happily works as underlying data is updated by the tasks. Likely it is the way I coded things, that can definitely do with some improvements.

When I 'optimized' things I complete the full task in 5 minutes (loading a database including many foreign key references from data coming from a third party) but needed about 8GB of RAM. The web app server otherwise peaks at about 1GB of RAM (I use netdata to keep track of system resources).

My solution was to run (once per month) this task where it could gladly take 24 hours if needs be in the background, using roughly 200mb of RAM for the tasks peak (instead of roughly 7GB!).

Shall I just arbritarily set a retry to the value of 200+ hours so that my solution works? Luckily the task is idempotent by design so does not really matter if it runs twice, but it looks to be that if the task (dependent on the number of records from a 3rd party expands, I will need to manually adjust this figure if it gets exceeded). Is there any way of outright disabling retries and instead triggering an email to admins for manual intervention in case that the task has failed?

Maybe I am abusing the system. I am open to any form of education in this area because I am far from expert. Many years ago I got aquainted with Apache Storm and don't remember there being this form of problem. Any info you could provide me here would probably be very suitable to go into the documentation.

**Comment by gorkemyontem** [comment]
@dnk8n Your retry threshold must be bigger than your time out. 
 ``` 
    'timeout': 4800,
    'retry': 4801,
```
